#ifndef ANOMALY_FULLSCREEN_SLOTS_HLSLI
#define ANOMALY_FULLSCREEN_SLOTS_HLSLI

// Anomaly-owned fullscreen bus. Packs do not pick t20–t25.
#define ANOMALY_FULLSCREEN_SCENE_SLOT 0
#define ANOMALY_FULLSCREEN_DEPTH_SLOT 1
#define ANOMALY_FULLSCREEN_VELOCITY_SLOT 2
#define ANOMALY_FULLSCREEN_REACTIVE_SLOT 3
// t4–t6 are slot-dependent: HDR slots bind GBuffer; AfterTonemap /
// AfterUpscale bind Keen tonemap inputs (avgLuminance / bloom / dirt).
#define ANOMALY_FULLSCREEN_GBUFFER0_SLOT 4
#define ANOMALY_FULLSCREEN_GBUFFER1_SLOT 5
#define ANOMALY_FULLSCREEN_GBUFFER2_SLOT 6
#define ANOMALY_FULLSCREEN_AVGLUM_SLOT 4
#define ANOMALY_FULLSCREEN_BLOOM_SLOT 5
#define ANOMALY_FULLSCREEN_DIRT_SLOT 6
#define ANOMALY_FULLSCREEN_PACK_SRV0_SLOT 7
#define ANOMALY_FULLSCREEN_PACK_SRV1_SLOT 8
#define ANOMALY_FULLSCREEN_PACK_SRV2_SLOT 9
#define ANOMALY_FULLSCREEN_CB_SLOT 6
#define ANOMALY_FULLSCREEN_UNIFORMS_SLOT 7
#define ANOMALY_FULLSCREEN_WRAP_SAMPLER_SLOT 2

#endif
