#ifndef ANOMALY_FULLSCREEN_SLOTS_HLSLI
#define ANOMALY_FULLSCREEN_SLOTS_HLSLI

// Anomaly-owned fullscreen bus. Packs do not pick t20–t25.
#define ANOMALY_FULLSCREEN_SCENE_SLOT 0
#define ANOMALY_FULLSCREEN_DEPTH_SLOT 1
#define ANOMALY_FULLSCREEN_VELOCITY_SLOT 2
#define ANOMALY_FULLSCREEN_REACTIVE_SLOT 3
#define ANOMALY_FULLSCREEN_CB_SLOT 6
#define ANOMALY_FULLSCREEN_UNIFORMS_SLOT 7

#endif
